[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "genomeprep"
authors = [{name = "Chang Lu", email = "luchang.thu@outlook.com"}]
dynamic = ["version", "description"]
